name: Maven Package

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - run: MAVEN_OPTS="-Xmx1563m" ./mvnw -B install
        -DskipTests -DskipITs -DskipDocs
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGES }}

    - run: MAVEN_OPTS="-Xmx1563m" ./mvnw -B -U deploy
        -DskipTests -DskipITs -DskipDocs
        -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGES }}
